plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.akasha.wrist'
    compileSdk 34

    defaultConfig {
        applicationId 'ai.akasha.wrist'
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
